# Dockerfile para el servicio de la base de datos
FROM mysql

ENV MYSQL_ROOT_PASSWORD tu_contraseña_de_root
ENV MYSQL_DATABASE jegaal
ENV MYSQL_USER jegaal
ENV MYSQL_PASSWORD root

EXPOSE 3306

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
